workflows:
android_release:
name: Android Release Build

environment:
  java: 17

scripts:
  - chmod +x ./gradlew
  - ./gradlew clean
  - ./gradlew assembleRelease

artifacts:
  - app/build/outputs/**/*.apk
  - app/build/outputs/**/*.aab
